### ISSUE TITLE
get percentage only when using surveydata 

### ISSUE THREAD

**Issue by tormodb** [kaz-yos/tableone#11]
Thanks for this great package! 

Is it possible to only output the percantages when using the package with survey data? The Ns that result from weighting are not appropriate, so an option to print unweighted Ns or only wieghted percentages would be very useful.

**Comment by tormodb** [comment]
I appologize for this, I just re-read the print command, and found the answer there. But, is it possible to omit the "n" (first row) of the table? (For the same reasons as above).

**Comment by kaz-yos** [comment]
Currently, the printing front end is common to both unweighted data and weighted data, so the "weighted n" will be presented as "n". Maybe there should be an option to change that. Meanwhile, a hacky solution is to obtain the matrix object from ```mat <- print(TableOne)``` and substitute or drop the first row.

**Comment by tormodb** [comment]
Thanks for the answer, I hacked this together by getting the frequencies from unweighted and then percentages for weighed then pasting them together, and keeping n from the unweighted tables. I can share the code if you are interested.

**Comment by kaz-yos** [comment]
Yes, please do share. It will be a great material for future users. Using gist, and putting a link here may be the easiest way to share.
