### ISSUE TITLE
Printing without = ... after factor variable

### ISSUE THREAD

**Issue by RenePosma** [kaz-yos/tableone#13]
Thank you for the great package! 

I was wondering whether it is possible not to report which level in the factor is used. For example (in bold):

  Female **= Female** (%)             16 (37.2)         15 (36.6)         1.00

Thanks in advance!

**Comment by kaz-yos** [comment]
There is no specific option for that. But you can capture the matrix output from print and do some string manipulation to achieve what you want. For example,

```R
tabMat <- print(tab1, printToggle = FALSE)
rownames(tabMat) <- gsub("=.*", "", rownames(tabMat))
tabMat
```

**Comment by kaz-yos** [comment]
This is supported by the ```dropEqual``` option as of version 0.9.0.
