### ISSUE TITLE
Clarify help text for argument "factorVars"

### ISSUE THREAD

**Issue by eribul** [kaz-yos/tableone#15]
It says for argument `factorVars` `?CreateTableOne` that:

```
Numerically coded variables that should be handled as categorical variables given as a character  
vector. If omitted, only factors are considered categorical variables. If all categorical variables in the
dataset are already factors, this option is not necessary. The variables specified here must also be 
specified in the vars argument.  
```

To me _If all categorical variables in the dataset are already factors, this option is not necessary_, sounds like a redundant specification of these variables have no effect, when it in reality means that such factor variables are relevelled (unused levels are dropped). 

Mayby this could be stated more clearly?
Mayby an additional message when a factor variable is relevelled this way could also be helpful?

**Comment by kaz-yos** [comment]
Thanks for the comment. A warning on releveling may be useful.

**Comment by kaz-yos** [comment]
The explanation was (hopefully) improved in the latest dev version. I'll submit this to CRAN shortly.

https://github.com/kaz-yos/tableone/commit/7d2d78224ab9e0545b7ff3be2fef885ff5e8fd69

**Comment by eribul** [comment]
Nice!
