### ISSUE TITLE
Leading white spaces

### ISSUE THREAD

**Issue by eribul** [kaz-yos/tableone#16]
I use the `CreateTableOne` together with the kable function from the knitr package. Unfortenately, leading spaces are then lost (unconditional on the `noSpace` argument to the print method).

I can solve this by the following (note: `gsub(" ", "&nbsp;", rownames(.), fixed = TRUE)`):

``` r
tableone::CreateTableOne(
  vars             = v_all,  
  strata           = "hip",  
  data             = d_paired,
  factorVars       = c(v_eq, "ingtyp_grov", "diagnos"),
  includeNA        = TRUE
) %>% 
print(
  printToggle      = FALSE,
  showAllLevels    = TRUE,
  cramVars         = "kon"
) %>% 
{data.frame(
  what             = gsub(" ", "&nbsp;", rownames(.), fixed = TRUE), ., 
  row.names        = NULL, 
  check.names      = FALSE, 
  stringsAsFactors = FALSE)} %>% 
knitr::kable()
```

But mayby this step could somehow be included in `print.TableOne` (at least if so wished through an argument to the function)?

**Comment by kaz-yos** [comment]
Thanks for your suggestion. In this case, do you want the leading spaces preserved for the row names only or all the spaces being used for alignment.

**Comment by eribul** [comment]
Probanly all but can check more closely on Friday!

**Comment by ghowoo** [comment]
It seems that the spaces in the value rows are preserved pretty well in my setting (kable to pdf). And I guess it complicating the situation by replacing white space to "&nbsp;", because it would show  "&nbsp;" in the R console.
