### ISSUE TITLE
format options

### ISSUE THREAD

**Issue by FlorianEndel** [kaz-yos/tableone#20]
Are there any possibilities to format the numerical output?
e.g. by passing options to the function _format_ as big.mark, small.mark, decimal.mark, ...

As far as I understand, most formatting is done with _sprintf_(?) which does give an straightforward option to format numbers differently...

**Comment by kaz-yos** [comment]
Thanks for your suggestions. I'll examine this. I would appreciate if you could give me numerical examples of what you want to see. Is it like 1,000.00?
