### ISSUE TITLE
option to print.TableOne (or CreateTableOne?) that allows comma-savvy printing

### ISSUE THREAD

**Issue by mikedolanfliss** [kaz-yos/tableone#23]
Though perhaps in the future (#22) number and percent (or smd, etc.) columns might be separated, in any case it'd be great to be able to flag to use comma values (e.g. "9,992 (50.2)") for printing. As you mentioned in #22, dplyr separation on "(", then formatting the as.numeric cells might be a workaround... but this seems like useful functionality if you're going to excel or word with it.

**Comment by vinhdizzo** [comment]
I too would like to second the option of adding commas in printing.  Here is my current hack assuming `pt1` is an object of class `print.TableOne`:

```r
add_comma <- function(pt1) {
  require(stringr)
  pt1_out <- pt1
  for(i in 1:ncol(pt1)) {
    cur_column <- pt1[, i]
    num_after <- str_extract(cur_column, '[0-9.]+\\b') %>% as.numeric %>% comma %>% str_replace('(\\.00|NA)', '') %>% trimws
    pt1_out[, i] <- str_replace(string=pt1_out[, i], pattern='[0-9.]+\\b', replacement=num_after)
  }
  return(pt1_out)
}
pt1 <- pt1 %>% add_comma
```

My suggestion in adding comma support is to modify `summary.CatTable` and `summary.ContTable` to not use `sprintf` but rather use R's `prettyNum` function, which has a `big.mark=','` argument to easily add commas.

Thanks for the work on TableOne!
