### ISSUE TITLE
Covariates missing impact outputs ?

### ISSUE THREAD

**Issue by AurelienMu** [kaz-yos/tableone#26]
Hello
I've found some differences between 2 adjusted tables output, and i was a little surprised because it was supposed to be the same table, but with some more covariates.

I searched and found that adjusted table, can varry in function of covariates specified, and more particularly if added covariates has missing values (NA)

Eg. 
Step 1 : just 1 covariate
```
                         1             2             3             p      test SMD   
  n                      152.77        155.31        154.70                          
  glycemie_g (mean (sd))   0.97 (0.22)   1.07 (0.37)   1.03 (0.29)  0.001       0.223
```

Step 2 : adding age (that has no NA)
```
  n                      152.77         155.31         154.70                           
  glycemie_g (mean (sd))   0.97 (0.22)    1.07 (0.37)    1.03 (0.29)   0.001       0.223
  age (mean (sd))         41.30 (11.88)  41.23 (11.46)  41.31 (10.53)  0.983       0.010
```
==> glycemie values are identical

Step 3 : adding imc_18, that has several NA
```
                         1              2              3              p      test SMD   
  n                      152.77         155.31         154.70                           
  glycemie_g (mean (sd))   0.97 (0.22)  **1.09 (0.39)**  1.03 (0.28)   0.001       0.223
  age (mean (sd))         41.10 (11.76)  41.27 (11.57)  40.60 (10.41)  0.983       0.010
  imc_18 (mean (sd))      30.01 (6.72)   28.67 (5.55)   24.12 (3.85)  <0.001       0.750
```
==> glycemie (and age) values have changed

I found this package very usefull to fastly compute big tables in a descent format, but i'am a bit suprised about this issue when using the adjusted table. Maybe i've forgotten something !?

EDIT : i'am not sure to mention well what i've done : i did a weighted adjustment (using AddMwToData  function and svydesign) and the issue is on the adjusted table.

**Comment by kaz-yos** [comment]
This is indeed very strange. Are you using the same ```svydesign``` object for Step 2 and Step 3?

**Comment by AurelienMu** [comment]
Thanks for the reply.
Here is the short code written for verification and i'am affraid that Svy-data-objects are the same :


c1<-c("glycemie_g")
c2<-c("glycemie_g", "age")
c3<-c("glycemie_g", "age","imc_18")

x1 <- CreateTableOne(vars = c1, strata = "age_debut_cat", data = data_metabo)
print(x1, test = TRUE, smd = TRUE)
x2 <- CreateTableOne(vars = c2, strata = "age_debut_cat", data = data_metabo)
print(x2, test = TRUE, smd = TRUE)
x3 <- CreateTableOne(vars = c3, strata = "age_debut_cat", data = data_metabo)
print(x3, test = TRUE, smd = TRUE)


data_metabo<- AddGPS(data = data_metabo, formula = age_debut_cat ~ imc+age+sexe_1)

## Add IPTW and MW
data_metabo <- AddMwToData(data = data_metabo, # dataset
txVar = "age_debut_cat", # treatment variable name
tx = c("1", "2", "3")) # treatment levels
## Check how weights are defined
head(data_metabo[c("age_debut_cat","PS_1","PS_2","PS_3","PS_assign","PS_min","iptw","mw")], 20)

library(survey)
metaboSvy <- svydesign(ids = ~ 1, data = data_metabo, weights = ~  mw)

y1 <- svyCreateTableOne(vars = c1, strata = "age_debut_cat", data = metaboSvy )
y2 <- svyCreateTableOne(vars = c2, strata = "age_debut_cat", data = metaboSvy )
y3 <- svyCreateTableOne(vars = c3, strata = "age_debut_cat", data = metaboSvy )

print(y1, test = TRUE, smd = TRUE)
print(y2, test = TRUE, smd = TRUE)
print(y3, test = TRUE, smd = TRUE)

**Comment by AurelienMu** [comment]
I just checked for categorical data, and there is no issue, with ou without missing data on covariates, the adjusted values are the same.

On continuous, there is another point : i feels like the test and SMD calculations aren't impacted by covariates missing values.
The only issue seems to be means/SD (and median[IQR]) The adjusted table is displayed for covariates complete data.
To be confirmed (but i'am pretty sure)

**Comment by chipmanj** [comment]
We've come across this issue as well and think we can point to what's going on ...

Referring to: https://github.com/cran/tableone/blob/master/R/modules-svy.R

svyMean #L84 and #L87 ... takes a formula of continuous variables (vars) and then applies svymean using option na.rm = TRUE.  Only complete cases across all formula variables are used for calculating the mean.  A solution could be to not use the formula that contains all continuos variables but to loop or apply svymean by each variable.

svySD and svyQuant are similarly approached and affected as mentioned above.  These all feed into svyContSummary.

Aside - would it be possible to have the na.rm = TRUE be an option that could be set in svyMean, svySD, and svyQuant?  We'd like the denominator of survey weights to not change based upon missing variables.

Thank you Yoshida for an excellent package.

**Comment by kaz-yos** [comment]
Many thanks to @AurelienMu and @chipmanj for tracking down the issue. I hope to address this at some point in the future, but can't promise a timeline due to other obligations... I would highly appreciate a pull request.

**Comment by chipmanj** [comment]
Hi @kaz-yos, sure we'll do a pull request.  And, please disregard the earlier aside about na.rm=TRUE.  Thanks again.
