### ISSUE TITLE
Is there a way to change the mean/sd to median and range in CreateTableOne() ?

### ISSUE THREAD

**Issue by SophiaJia** [kaz-yos/tableone#29]
CreateTableOne() gives me mean/sd  but we use median more often. I kind of know how to change it in CreateContTable, but I didn't find the funcNanmes argument in the CreateTableOne().

**Comment by kaz-yos** [comment]
?print.TableOne should give you the information you need.

**Comment by SophiaJia** [comment]
Thanks for your reply, the only thing I found related in ?print.TableOne is :

>  minMax	: Whether to use [min,max] instead of [p25,p75] for nonnormal variables. The default is FALSE.

However, I still wouldn't replace mean/sd to the median(range). Do you mind specify when you get a chance?

Thank you very much !

**Comment by kaz-yos** [comment]
Please check the ```nonnormal``` specification.
https://github.com/kaz-yos/tableone/blob/fe1671e7d3c7d90824602d07e47f033906ce47e2/inst/doc/introduction.Rmd#summarizing-nonnormal-variables

**Comment by SophiaJia** [comment]
Thank you so much, it works very well, I really appreciate your time!
