### ISSUE TITLE
Nonnormal argument missing, and multiple group summary problem

### ISSUE THREAD

**Issue by Breal76** [kaz-yos/tableone#36]
Hi, I'm following the excellent [intro to tableone](https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html) in RStudio (1.1.447) and R version 3.5.0 but hitting a few errors:

1. Summarizing nonnormal variables: "Let’s do it with the nonnormal argument to the print() method". My code:

`print(tab2, showAllLevels = TRUE, nonnormal = "notnormalVars")`

The nonnormal argument doesn't seem to exist. The nonnormal argument is not even suggested in the command prompt pop ups. All of my non-normal variables are still being summarised with mean and sd (i.e. not median and IQR). Is base print() meant here? Feels like I'm missing a package install.

2. Multiple group summary.  I'm grouping cases and want to summarise by group. My group is a binary int variable (0 or 1) called "known_software_client" (I summarise this as a factor in catVars(), but I don't think that's relevant for my problem). When I use this as a strata...

`tab3 <- CreateTableOne(vars = myVars, strata = "known_software_client", data = ch_d, factorVars = catVars)` 

I get an error:

`Error in parse(text = x, keep.source = FALSE) : 
  <text>:1:12: unexpected symbol
1: ~ Provider Ownership
               ^`
Not really sure what's going on here. Is this because there is a space in the variable "Provider Ownership" in my myVars list? When I include `` around the variable name (i.e. "`Provider Ownership`" it then doesn't even recognise the variable in my dataset. Besides, when I use 

`tab2<- CreateTableOne(vars = myVars, data = ch_d, factorVars = catVars)`

There is no problem. The problem only seems to occur when I use strata. 

Think these are two separate issues but just including them in one message. Any help welcome! Thanks and great package, i've been looking for something like this for MONTHS!!

**Comment by kaz-yos** [comment]
Do you actually have a variable named "notnormalVars"? Please try ?print.TableOne to see if the help shows up.

**Comment by Breal76** [comment]
Yes I have a vector named "notnormalVars", created like this:

`notnormalVars <- c("ProviderDuration","LocationDuration","Care homes beds", "ave_weekly_fee_location_total","n.neighbour_dist_in_meters","density_10k")`

?print.TableOne does indeed describe the nonnormal argument for the class 'TableOne'. Am I using it incorrectly?

**Comment by kaz-yos** [comment]
```
print(tab2, showAllLevels = TRUE, nonnormal = notnormalVars)
```

**Comment by kaz-yos** [comment]
Can you try making the "known_software_client" variable a factor beforehand and not include it in the ```factorVars``` vector.

**Comment by Breal76** [comment]
Same error. 

```
ch_d$known_software_client <- as.factor(ch_d$known_software_client)

myVars <- c("Provider Ownership Type","ProviderDuration","Provider Region",
            "Location Region", "LocationDuration","Location Latest Overall Rating","ccg_rating_17",
            "Care homes beds","nursing","LB Percentage of Self Funders","ave_weekly_fee_location_total", "n.neighbour_dist_in_meters","density_10k" )

catVars <- c("location_hasurl","provider_hasurl") 

tab3 <- CreateTableOne(vars = myVars, strata = "known_software_client", data = ch_d, factorVars = catVars)
```

Error:
`Error in parse(text = x, keep.source = FALSE) : 
  <text>:1:12: unexpected symbol
1: ~ Provider Ownership
               ^`

This is the same error whether I include the strata variable within factorVars, vars, or neither.  Feels like its not liking the space between Provider and Owner (the formatting in this post is a bit off... the ^ symbol in the RStudio output console is underneath the 'w' in Ownership.

**Comment by Breal76** [comment]
Just to close this second question off, I removed the spaces from all variable names using:

`names(ch_d) <- make.names(names(ch_d), unique = TRUE)`

This basically replaces spaces in variable names with dots. This seems to have done the trick, I can now summarise by group.
