### ISSUE TITLE
Numbers with comma at thousands 

### ISSUE THREAD

**Issue by jdratto** [kaz-yos/tableone#51]
Is there any way to have the table include a comma at the thousands place.  Current output is this
alk.phos (mean (SD)) "1982.66 (2140.39)"

Is there a way to get this instead? alk.phos (mean (SD)) "1,982.66 (2,140.39)"

**Comment by kaz-yos** [comment]
It’s not implemented as of now. Perhaps it’s possible to implement that as an argument for which users supply a custom function to format the number.
