### ISSUE TITLE
TableOne treats expresses my continous variables as categorical

### ISSUE THREAD

**Issue by eguti** [kaz-yos/tableone#57]
Once I define some factorVars, all myVars are treated as categorical in the table. I have checked, and they are continous in the dataframe. I attach code and result. Thank you very much.
[tableone categorical continous variables trouble.docx](https://github.com/kaz-yos/tableone/files/4034594/tableone.categorical.continous.variables.trouble.docx)

**Comment by ndevln** [comment]
Can you run `lapply(data, class)`?

My best guess is that your data is labelled. 

Greetings
Alex

PS: Please don't upload word documents. Just use a textfile (.txt), markdown (.md) or somthing like https://pastebin.com/ If it fits you can also just paste it here.

**Comment by proshano** [comment]
i can confirm this happens to me also with the most current cran version
