### ISSUE TITLE
Digits argument broken

### ISSUE THREAD

**Issue by SimonStolz** [kaz-yos/tableone#70]
```
## Generating data for example
set.seed(1)
x <- rnorm(50, 50, 34)
set.seed(2)
y <- rnorm(50, 70, 34)
d <- rbind(cbind(G = 1, x),
           cbind(G = 0, y)) %>% as.data.frame()
```
when now displaying the table, it makes no difference what `digits` I specify in the argument. `pDigits` works fine, but `digits` has no impact on the output. It always rounded to 2 decimal places!

`print(CreateTableOne(vars = "x", strata="G", data = d), digits = 5, pDigits = 5)`

>  x (mean (sd)) 72.35 (38.41) 53.42 (28.27)  0.00602  

`print(CreateTableOne(vars = "x", strata="G", data = d), digits = 1, pDigits = 5)`
>  x (mean (sd)) 72.35 (38.41) 53.42 (28.27)  0.00602

**Comment by ndevln** [comment]
Hi,

`print.TableOne()` has no `digits` argument. Please use `contDigits` for continuos variables.  Proportions (i.e. percentages) are controlled with `catDigits`. This behaviour was seperated to provide more flexibility.

https://www.rdocumentation.org/packages/tableone/versions/0.11.2/topics/print.TableOne

Greetings
Alex

**Comment by SimonStolz** [comment]
Apologies - I could swear I saw this argument! Thanks a lot Alex, this worked perfectly!
